import { useState, type FormEvent } from 'react';
import { z } from 'zod';
import { useDomainResource } from '../../shared/ipc/useDomainResource';
type DetailItem = { id: string; title: string; done: boolean };
type Domain = { id: string; name: string; summary: string; milestones: DetailItem[]; tasks: DetailItem[] };
const initialDomains: Domain[] = [{ id: 'd1', name: 'Java/Kafka 深化', summary: '深化分布式系统与消息中间件的工程实践。', milestones: [{ id: 'm1', title: '掌握 Kafka 核心架构', done: true }, { id: 'm2', title: '完成性能调优实践', done: true }, { id: 'm3', title: '梳理故障恢复机制', done: false }, { id: 'm4', title: '输出团队分享', done: false }], tasks: [{ id: 't1', title: '完成消费者组再平衡实验', done: false }] }, { id: 'd2', name: 'A股量化方法论', summary: '建立可验证、可复盘的投资研究框架。', milestones: [{ id: 'm5', title: '建立估值框架', done: true }, { id: 'm6', title: '完成因子回测', done: false }, { id: 'm7', title: '形成交易检查清单', done: false }], tasks: [{ id: 't2', title: '阅读《估值的艺术》第3章', done: false }] }];
const detailSchema = z.object({ id: z.string().min(1).max(100), title: z.string().min(1).max(200), done: z.boolean() }).strict();
const domainsSchema = z.array(z.object({ id: z.string().min(1).max(100), name: z.string().min(1).max(100), summary: z.string().max(1000), milestones: z.array(detailSchema), tasks: z.array(detailSchema) }).strict());

/** Side effects: persists domains, milestones and tasks through typed IPC to SQLite; workspace selection remains local. */
export function Learning() {
  const [domains, setDomains] = useDomainResource('learning.domains', domainsSchema, initialDomains); const [activeId, setActiveId] = useState<string | null>(null); const [message, setMessage] = useState(''); const active = domains.find((domain) => domain.id === activeId);
  const addDomain = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const name = String(new FormData(form).get('name') ?? '').trim(); if (!name || name.length > 100 || domains.some((domain) => domain.name === name)) return setMessage('请输入不重复的 1–100 字领域名称'); setDomains((items) => [...items, { id: crypto.randomUUID(), name, summary: '', milestones: [], tasks: [] }]); form.reset(); setMessage('学习领域已加入本次运行状态'); };
  const toggle = (kind: 'milestones' | 'tasks', id: string) => setDomains((items) => items.map((domain) => domain.id !== activeId ? domain : { ...domain, [kind]: domain[kind].map((item) => item.id === id ? { ...item, done: !item.done } : item) }));
  const addDetail = (event: FormEvent<HTMLFormElement>, kind: 'milestones' | 'tasks') => { event.preventDefault(); const form = event.currentTarget; const title = String(new FormData(form).get('title') ?? '').trim(); if (!title || title.length > 200) return; setDomains((items) => items.map((domain) => domain.id !== activeId ? domain : { ...domain, [kind]: [...domain[kind], { id: crypto.randomUUID(), title, done: false }] })); form.reset(); };
  if (active) return <DomainWorkspace domain={active} onBack={() => setActiveId(null)} onToggle={toggle} onAdd={addDetail} />;
  return <div className="learning-view">{message && <div role="status" className="status-message">{message}</div>}<section className="card learning-form-card"><h2>新建学习领域</h2><form onSubmit={addDomain}><input name="name" maxLength={100} required placeholder="学习领域名称" /><button className="command-button">保存</button></form></section><div className="domain-grid">{domains.map((domain) => { const done = domain.milestones.filter((item) => item.done).length; const total = domain.milestones.length; const percent = total ? done / total * 100 : 0; return <button className="card domain-card" onClick={() => setActiveId(domain.id)} key={domain.id}><h2>#{domain.name}</h2><p className="small">里程碑 {done}/{total}</p><div className="progress"><div style={{ width: `${percent}%` }} /></div></button>; })}</div></div>;
}
type WorkspaceProps = { domain: Domain; onBack: () => void; onToggle: (kind: 'milestones' | 'tasks', id: string) => void; onAdd: (event: FormEvent<HTMLFormElement>, kind: 'milestones' | 'tasks') => void };
/** Side effects: invokes workspace callbacks; no direct external writes. */
function DomainWorkspace({ domain, onBack, onToggle, onAdd }: WorkspaceProps) { const done = domain.milestones.filter((item) => item.done).length; return <div className="domain-workspace"><header><button className="back-button" onClick={onBack}>← 返回领域列表</button><div><h2>{domain.name}</h2><p className="small">里程碑进度 {done}/{domain.milestones.length}（自动派生）</p></div></header><div className="grid grid-2"><section className="card"><h2>基本信息与里程碑</h2><p>{domain.summary || '暂无领域说明'}</p><DetailList items={domain.milestones} onToggle={(id) => onToggle('milestones', id)} /><DetailForm label="新增里程碑" onSubmit={(event) => onAdd(event, 'milestones')} /></section><section className="card"><h2>阶段性任务</h2><p className="small">任务天然属于当前领域，并将进入日程待排期池。</p><DetailList items={domain.tasks} onToggle={(id) => onToggle('tasks', id)} /><DetailForm label="新增阶段任务" onSubmit={(event) => onAdd(event, 'tasks')} /></section></div></div>; }
/** Side effects: invokes completion callback. */
function DetailList({ items, onToggle }: { items: DetailItem[]; onToggle: (id: string) => void }) { return <div className="detail-list">{items.map((item) => <label className={item.done ? 'done' : ''} key={item.id}><input type="checkbox" checked={item.done} onChange={() => onToggle(item.id)} /> <span>{item.title}</span></label>)}</div>; }
/** Side effects: invokes form callback. */
function DetailForm({ label, onSubmit }: { label: string; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="detail-form" onSubmit={onSubmit}><input name="title" maxLength={200} required placeholder={label} /><button className="command-button">添加</button></form>; }
