import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const html = readFileSync('life_os_prototype.html', 'utf8');
const spec = readFileSync('docs/spec.md', 'utf8');
const modules = ['dashboard','compass','work','schedule','finance','items','network','trade','learning'];
for (const module of modules) assert.match(html, new RegExp(`id="view-${module}"`), `缺少模块 ${module}`);
assert.match(html, /e\.altKey\s*&&\s*e\.code==='Space'/, '缺少快捷键');
assert.match(html, /localStorage/, '缺少本地持久化');
assert.match(html, /function sanitizeStoredHTML/, '缺少存储内容清洗');
assert.match(html, /function submitPalette/, '快捷录入未接入业务');
assert.match(html, /function submitWorkTask/, '工作模块缺少独立新增入口');
assert.match(html, /function submitScheduleEvent/, '日程模块缺少独立新增入口');
assert.match(html, /id="lifeSchedulePreview"/, '生活日程缺少时间线预览');
assert.match(html, /id="lifePreviewDate"/, '生活日程缺少按日预览日期');
assert.match(html, /lifeSchedules\.filter\(item=>lifeScheduleOccursOn/, '生活时间线没有汇总当日全部任务');
for (const frequency of ['daily','weekly','monthly','biweekly']) assert.match(html, new RegExp(`value="${frequency}"`), `缺少生活日程频率 ${frequency}`);
assert.doesNotMatch(html, /id="scheduleEnd"/, '生活日程不应要求截止时间');
for (const view of ['day','week','month']) assert.match(html, new RegExp(`id="schedule-${view}"`), `日程缺少 ${view} 视图`);
for (const module of ['work','learning','items','network']) assert.match(html, new RegExp(`class="pool-module" data-module="${module}"`), `待排期池缺少 ${module} 分组`);
assert.match(html, /draggable="true"/, '待排期任务不可拖动');
assert.match(html, /function dropScheduleTask/, '日程缺少拖放排期动作');
assert.match(html, /function returnScheduledTaskToPool/, '已排期任务无法还原到任务池');
assert.match(html, /data-scheduled-id/, '已排期任务不可再次拖动');
assert.match(html, /Math\.round\(raw\/15\)\*15/, '连续时间画布未提供 15 分钟吸附');
assert.match(html, /function updateScheduledTaskTime/, '日视图缺少分钟级时间调整');
assert.match(html, /class="event-resize"/, '日程事件缺少时长调整拖柄');
assert.match(html, /class="now-line"/, '日视图缺少当前时间线');
assert.match(html, /function renderLifeScheduleTemplates/, '生活日程缺少模板管理区');
assert.match(html, /task\.immutable\?'':'draggable/, '生活日程未禁止拖动');
assert.match(html, /\.schedule-tab\{appearance:none;border:0;outline:0/, '日周月切换按钮仍有原生边界');
assert.match(html, /actualPct>timePct\?' alert-amber pulse-amber'/, '预算消费进度领先时未触发预警');
assert.match(html, /id="budgetPace"/, '预算卡未展示消费与时间进度差');
assert.match(html, /data-type="食物"/, '物品模块缺少食物分类');
assert.match(html, /id="itemLocation"/, '物品缺少存放位置');
assert.match(html, /function refreshFoodExpiry/, '食物缺少保质期预警计算');
assert.match(html, /id="foodList"/, '食物没有完整展示清单');
assert.match(html, /#view-items\.active\{display:grid;grid-template-columns:minmax\(0,1fr\) 310px/, '物品新增表单未放置在右侧栏');
assert.match(html, /id="itemFormCard"/, '物品新增表单缺少右侧栏定位标识');
assert.match(html, /id="learningFormCard"/, '学习新增表单缺少右侧栏定位标识');
assert.match(html, /<select class="styled-select" id="learnSub"/, '学习关联领域没有使用统一下拉样式');
assert.match(html, /\.styled-select\{position:absolute;opacity:0;pointer-events:none/, '原生学习领域列表未被隐藏');
assert.match(html, /\.custom-select-menu\{display:none;position:absolute[^}]*background:#FFFFFF/, '学习领域自定义下拉列表不是白色背景');
assert.match(html, /id="learnSubMenu"/, '学习领域仍使用原生弹出列表');
assert.match(html, /function refreshLearningDomainOptions/, '学习领域下拉不会随领域列表更新');
assert.match(html, /function openDomainDetail/, '学习领域卡片无法打开详情');
assert.match(html, /function upgradeLearningDomainCards/, '旧版学习领域卡片无法迁移为可点击卡片');
assert.match(html, /id="domainMilestoneList"/, '学习领域详情缺少里程碑');
assert.match(html, /id="domainStageTaskList"/, '学习领域详情缺少阶段性任务');
assert.match(html, /class="domain-workspace-grid"/, '学习领域详情不是整页工作区');
assert.match(html, /← 返回领域列表/, '学习领域工作区缺少返回领域列表');
assert.match(html, /id="tradeReviewInput"/, '投资每日复盘缺少模块内录入框');
assert.match(html, /function submitTradeReview/, '投资每日复盘缺少保存动作');
for (const quadrant of ['Q1','Q2','Q3','Q4']) assert.match(html, new RegExp(`data-quadrant="${quadrant}"`), `工作待排期任务缺少 ${quadrant}`);
assert.doesNotMatch(html, /onclick="openPalette\(\); selectCat\('(?:work|schedule)'/, '模块新增按钮不得依赖快捷面板');
assert.match(spec, /函数副作用约定/, '规格未声明副作用');
assert.doesNotMatch(html, /prompt\s*\(/, '禁止 prompt 编辑');
console.log('Life-OS 静态规格校验通过：9 模块、快捷录入、持久化、安全边界。');
