import { useState, type FormEvent } from 'react';
import { z } from 'zod';
import { useDomainResource } from '../../shared/ipc/useDomainResource';
import { priceAlert } from './tradeModel';
type Watch = { id: string; code: string; name: string; target: number; safety: number; current: number };
type Position = { id: string; watchlistId: string; price: number; stop?: number };
type Review = { date: string; content: string };
const initialWatch: Watch[] = [{ id: 'w1', code: '600519', name: '贵州茅台', target: 1680, safety: 1450, current: 1442 }, { id: 'w2', code: '002230', name: '科大讯飞', target: 40, safety: 34, current: 41.2 }];
const watchSchema = z.array(z.object({ id: z.string().min(1).max(100), code: z.string().regex(/^[A-Za-z0-9._-]{1,16}$/), name: z.string().min(1).max(100), target: z.number().positive(), safety: z.number().nonnegative(), current: z.number().nonnegative() }).strict());
const positionSchema = z.array(z.object({ id: z.string().min(1).max(100), watchlistId: z.string().min(1).max(100), price: z.number().positive(), stop: z.number().positive().optional() }).strict());
const reviewSchema = z.array(z.object({ date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), content: z.string().min(1).max(1000) }).strict());

/** Side effects: persists watchlist, positions and reviews through typed IPC to SQLite; performs no market requests. */
export function Trade() {
  const [watchlist, setWatchlist] = useDomainResource('trade.watchlist', watchSchema, initialWatch); const [positions, setPositions] = useDomainResource('trade.positions', positionSchema, [{ id: 'pos1', watchlistId: 'w2', price: 38.2, stop: 34 }] as Position[]); const [reviews, setReviews] = useDomainResource('trade.reviews', reviewSchema, [{ date: '2026-07-25', content: '大盘震荡，茅台触及安全价，暂不加仓观察量能' }] as Review[]); const [message, setMessage] = useState('');
  const addWatch = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const code = String(data.get('code') ?? '').trim(); const name = String(data.get('name') ?? '').trim(); const target = Number(data.get('target')); const safety = Number(data.get('safety')); const current = Number(data.get('current')); if (!/^[A-Za-z0-9._-]{1,16}$/.test(code) || !name || ![target, safety, current].every(Number.isFinite) || safety >= target) return setMessage('请填写有效代码、名称和价格，且安全价低于目标价'); if (watchlist.some((item) => item.code === code)) return setMessage('该代码已在观察列表'); setWatchlist((items) => [...items, { id: crypto.randomUUID(), code, name, target, safety, current }]); form.reset(); setMessage('已加入观察列表（运行态）'); };
  const addPosition = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const watchlistId = String(data.get('watchlistId')); const price = Number(data.get('price')); const stop = Number(data.get('stop')); if (!watchlist.some((item) => item.id === watchlistId) || !Number.isFinite(price) || price <= 0 || (stop && stop <= 0)) return setMessage('持仓必须选择观察列表标的并填写有效价格'); setPositions((items) => [...items, { id: crypto.randomUUID(), watchlistId, price, stop: stop || undefined }]); form.reset(); setMessage('持仓已加入本次运行状态'); };
  const saveReview = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const content = String(new FormData(form).get('content') ?? '').trim(); if (!content || content.length > 1000) return setMessage('复盘内容应为 1–1000 个字符'); const date = new Date().toLocaleDateString('sv-SE'); setReviews((items) => [{ date, content }, ...items.filter((item) => item.date !== date)]); form.reset(); setMessage('今日复盘已按日期更新（运行态）'); };
  return <div className="trade-view"><section className="card trade-sop"><p className="small">SOP：观察列表 → 到达安全价 → 纪律建仓 → 策略卖出/止损 → 每日复盘</p></section>{message && <div role="status" className="status-message">{message}</div>}<section className="card trade-card"><h2><span>观察列表</span><span className="tag">手动价格 · 不提供建议</span></h2><form className="compact-form" onSubmit={addWatch}><input name="code" placeholder="代码" required /><input name="name" placeholder="名称" required /><input name="target" type="number" step="0.01" placeholder="目标价" required /><input name="safety" type="number" step="0.01" placeholder="安全价" required /><input name="current" type="number" step="0.01" placeholder="现价" required /><button className="command-button">加入观察列表</button></form><div className="watch-head"><span>代码/名称</span><span>目标价</span><span>安全价</span><span>现价</span><span>状态</span></div>{watchlist.map((item) => <WatchRow item={item} key={item.id} />)}</section><section className="card trade-card"><h2><span>持仓管理</span><span className="tag">仅限观察列表选股</span></h2><form className="compact-form" onSubmit={addPosition}><select name="watchlistId" aria-label="观察列表标的">{watchlist.map((item) => <option value={item.id} key={item.id}>{item.code} {item.name}</option>)}</select><input name="price" type="number" step="0.01" min="0.01" required placeholder="建仓价" /><input name="stop" type="number" step="0.01" min="0.01" placeholder="止损价" /><button className="command-button">分批建仓</button></form>{positions.map((position) => { const item = watchlist.find((watch) => watch.id === position.watchlistId)!; return <div className="position-row" key={position.id}><span className="mono">{item.code} {item.name}</span><span>建仓 ¥{position.price.toFixed(2)} · 止损 {position.stop ? `¥${position.stop.toFixed(2)}` : '未设置'}</span></div>; })}</section><section className="card"><h2>每日复盘（按日唯一）</h2><form className="review-form" onSubmit={saveReview}><input name="content" maxLength={1000} required placeholder="记录大盘/持仓观察，以及有无操作和逻辑" /><button className="command-button">保存今日复盘</button></form><div className="timeline">{reviews.map((review) => <div className="timeline-item" key={review.date}><div className="timeline-meta">{review.date}</div><div className="timeline-title">{review.content}</div></div>)}</div></section></div>;
}
/** Side effects: none. */
function WatchRow({ item }: { item: Watch }) { const alert = priceAlert(item.current, item.target, item.safety); return <div className={`watch-row ${alert}`}><strong>{item.code} {item.name}</strong><span>¥{item.target}</span><span>¥{item.safety}</span><span>¥{item.current}</span><span className={`chip ${alert === 'target' ? 'crimson' : alert === 'safety' ? 'sky' : 'amber'}`}>{alert === 'target' ? '已达目标价' : alert === 'safety' ? '已跌破安全价' : '观察中'}</span></div>; }
